version: "3"
services:
  db:
    image: postgres:13.3
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_USER: db_prisma
      POSTGRES_PASSWORD: db_prisma1
      POSTGRES_DB: uve_stocks
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - uve-stocks-network
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - cache:/data
    networks:
      - uve-stocks-network
volumes:
  cache:
    driver: local
networks:
  uve-stocks-network:
