import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { APP_NAME } from "./lib/globals";
import { ThemeProvider, BaseStyles } from "@primer/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: APP_NAME,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <BaseStyles>
          <body className={`${inter.className} min-h-screen`}>{children}</body>
        </BaseStyles>
      </ThemeProvider>
    </html>
  );
}
