import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { APP_NAME } from "./_lib/globals";
import { ThemeProvider, BaseStyles } from "@primer/react";
import { Wrapper } from "./_components";
import { getBusinesses } from "./_lib/business";
import { supabaseClientServer } from "./_lib/supabase-server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: APP_NAME,
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { businesses } = await getBusinesses();

  const { data } = await supabaseClientServer.auth.getUser();

  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen`}>
        <ThemeProvider>
          <BaseStyles>
            {businesses && (
              <Wrapper businesses={businesses} currentUser={data.user}>
                {children}
              </Wrapper>
            )}
          </BaseStyles>
        </ThemeProvider>
      </body>
    </html>
  );
}
