import { BaseStyles, ThemeProvider } from "@primer/react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Wrapper } from "./_components";
import { APP_NAME } from "./_lib/globals";
import { createServerSupabaseClient } from "./_lib/supabase-server";
import "./globals.css";
import "@cloudscape-design/global-styles/index.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: APP_NAME,
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { data } = await createServerSupabaseClient().auth.getUser();

  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen`}>
        <ThemeProvider>
          <BaseStyles>
            <Wrapper currentUser={data.user}>{children}</Wrapper>
          </BaseStyles>
        </ThemeProvider>
      </body>
    </html>
  );
}
